```{r}
library(tidyverse)
library(datasets.load)
```

```{r}
desc <- read_csv("descriptions.csv")
```


```{r}
desc %>% select(dataset, note, technique) -> desc
desc
```

grab the ones that are already in assignments/rdata

```{r}
list.files(path = "../assignments/rdata/", pattern = "*.[qR]md") %>% 
  enframe(name = NULL, value = "fname") %>% 
  separate_wider_delim(fname, delim = "_", 
                       names = c("technique", "package", "dataset_name"), 
                       too_few = "align_start") %>%
  drop_na() %>% 
  mutate(dataset_name = str_remove(dataset_name, ".[qR]md$")) %>% 
  mutate(dataset = str_c(package, "::", dataset_name)) %>% 
  select(technique, dataset)-> rdata_files
rdata_files
```

select the ones in desc that are not in rdata_files

```{r}
desc %>% 
  select(dataset, technique, note) %>% 
  separate_rows(technique, sep = ",") %>% 
  anti_join(rdata_files, join_by(technique, dataset)) %>% 
  # filter(str_detect(technique, "categorical")) %>% # this line to select a technique, or use find_these
  slice_sample(prop = 1) %>% 
  View()
# %>% 
  # arrange(technique)
```

diff between installed.packages and the ones in description

```{r}
desc %>% 
  separate_wider_delim(dataset, names = c("package", "dataset_name"), delim = "::",
                       too_few = "align_start") %>% 
  count(package) -> desc_packages
desc_packages
```

```{r}
installed.packages() %>% as_tibble() %>% 
  select(package = Package) -> installed_packages
installed_packages %>% arrange(package)
```

```{r}
desc_packages %>% anti_join(installed_packages) %>% 
  slice_sample(n = 10)
```

